# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/ibm-watson-cxa/EOCore.git'
source 'https://github.com/ibm-watson-cxa/DigitalAnalytics.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'KitchenSinkNew' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'DigitalAnalytics'


  # Pods for KitchenSinkNew

  target 'KitchenSinkNewTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
